import { collection, addDoc } from 'firebase/firestore';
import { db } from './firebase';

const vans = [
  {
    title: 'Toyota Hiace 2015 - Self-Contained Certified',
    price: 18500,
    year: 2015,
    mileage: 145000,
    location: 'Auckland',
    region: 'North Island',
    type: 'Campervan',
    capacity: 2,
    selfContained: true,
    featured: true,
    description: 'Perfect backpacker van! Self-contained certified with fresh WOF. Fully equipped with solar panels, fridge, and sleeping area. Ready for your NZ adventure!',
    imageUrl: 'https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=800',
    features: ['Self-Contained', 'Solar 200W', 'Fridge', 'Fresh WOF', 'Queen Bed', 'Kitchen'],
    seller: { name: 'Mike Thompson', rating: 4.9, phone: '+64 21 123 4567', email: 'mike@example.com' },
    buyBack: true,
    views: 234,
    postedDays: 3,
    wofExpiry: '2025-11-15',
    regoExpiry: '2025-09-20',
    createdAt: new Date()
  },
  {
    title: 'Mitsubishi Delica 2008 - 4WD Adventure',
    price: 12800,
    year: 2008,
    mileage: 198000,
    location: 'Queenstown',
    region: 'South Island',
    type: 'Van',
    capacity: 4,
    selfContained: false,
    featured: true,
    description: '4WD Delica, perfect for adventures! Pop-top roof for extra space. Great condition.',
    imageUrl: 'https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=800',
    features: ['4WD', 'Pop-top', 'Sleeps 4', 'Diesel', 'Manual'],
    seller: { name: 'Emma Wilson', rating: 4.7, phone: '+64 27 987 6543', email: 'emma@example.com' },
    buyBack: false,
    views: 189,
    postedDays: 5,
    wofExpiry: '2025-08-10',
    regoExpiry: '2025-07-15',
    createdAt: new Date()
  },
  {
    title: 'Ford Transit 2018 - Luxury Conversion',
    price: 35000,
    year: 2018,
    mileage: 89000,
    location: 'Wellington',
    region: 'North Island',
    type: 'Campervan',
    capacity: 2,
    selfContained: true,
    featured: false,
    description: 'Professional conversion with high-end finishes. Self-contained certified.',
    imageUrl: 'https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=800',
    features: ['Self-Contained', 'Solar 400W', 'Shower', 'Toilet', 'Hot Water', 'Heating'],
    seller: { name: 'John Smith', rating: 5.0, phone: '+64 22 345 6789', email: 'john@example.com' },
    buyBack: true,
    views: 456,
    postedDays: 1,
    wofExpiry: '2026-01-20',
    regoExpiry: '2025-12-15',
    createdAt: new Date()
  },
  {
    title: 'Mazda Bongo 2006 - Budget Friendly',
    price: 8500,
    year: 2006,
    mileage: 215000,
    location: 'Christchurch',
    region: 'South Island',
    type: 'Van',
    capacity: 2,
    selfContained: false,
    featured: false,
    description: 'Perfect starter van for backpackers. Reliable and economical.',
    imageUrl: 'https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=800',
    features: ['Pop-top', 'Bed', 'Curtains', 'Storage', 'Economical'],
    seller: { name: 'Sarah Brown', rating: 4.6, phone: '+64 21 567 8901', email: 'sarah@example.com' },
    buyBack: false,
    views: 123,
    postedDays: 7,
    wofExpiry: '2025-06-30',
    regoExpiry: '2025-05-20',
    createdAt: new Date()
  },
  {
    title: 'Volkswagen Crafter 2019 - Modern Living',
    price: 42000,
    year: 2019,
    mileage: 65000,
    location: 'Auckland',
    region: 'North Island',
    type: 'Campervan',
    capacity: 2,
    selfContained: true,
    featured: true,
    description: 'Modern conversion with all amenities. Like new condition!',
    imageUrl: 'https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=800',
    features: ['Self-Contained', 'Solar 600W', 'Lithium Battery', 'Shower', 'AC', 'Heating'],
    seller: { name: 'David Lee', rating: 4.9, phone: '+64 27 234 5678', email: 'david@example.com' },
    buyBack: true,
    views: 567,
    postedDays: 2,
    wofExpiry: '2026-03-15',
    regoExpiry: '2026-02-10',
    createdAt: new Date()
  },
  {
    title: 'Nissan Caravan 2012 - Family Size',
    price: 15500,
    year: 2012,
    mileage: 168000,
    location: 'Hamilton',
    region: 'North Island',
    type: 'Van',
    capacity: 4,
    selfContained: false,
    featured: false,
    description: 'Spacious van perfect for families. Plenty of storage.',
    imageUrl: 'https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=800',
    features: ['Sleeps 4', 'Kitchen', 'Fridge', 'Sink', 'Storage'],
    seller: { name: 'Lisa Chen', rating: 4.8, phone: '+64 21 876 5432', email: 'lisa@example.com' },
    buyBack: false,
    views: 234,
    postedDays: 4,
    wofExpiry: '2025-09-25',
    regoExpiry: '2025-08-18',
    createdAt: new Date()
  },
  {
    title: 'Mercedes Sprinter 2017 - Premium',
    price: 38500,
    year: 2017,
    mileage: 95000,
    location: 'Dunedin',
    region: 'South Island',
    type: 'Campervan',
    capacity: 2,
    selfContained: true,
    featured: true,
    description: 'Premium Mercedes with professional conversion. Excellent condition.',
    imageUrl: 'https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=800',
    features: ['Self-Contained', 'Solar', 'Shower', 'Toilet', 'Diesel Heating', 'Premium Interior'],
    seller: { name: 'Tom Anderson', rating: 4.9, phone: '+64 22 456 7890', email: 'tom@example.com' },
    buyBack: true,
    views: 389,
    postedDays: 3,
    wofExpiry: '2025-12-20',
    regoExpiry: '2025-11-15',
    createdAt: new Date()
  },
  {
    title: 'Toyota Regius 2010 - Reliable Choice',
    price: 11200,
    year: 2010,
    mileage: 178000,
    location: 'Tauranga',
    region: 'North Island',
    type: 'Van',
    capacity: 3,
    selfContained: false,
    featured: false,
    description: 'Solid reliable van with basic conversion. Great for touring.',
    imageUrl: 'https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=800',
    features: ['Sleeps 3', 'Kitchen', 'Storage', 'Rock & Roll Bed'],
    seller: { name: 'Rachel Green', rating: 4.5, phone: '+64 27 345 6789', email: 'rachel@example.com' },
    buyBack: false,
    views: 156,
    postedDays: 6,
    wofExpiry: '2025-07-15',
    regoExpiry: '2025-06-20',
    createdAt: new Date()
  },
  {
    title: 'Fiat Ducato 2016 - Self-Contained',
    price: 28500,
    year: 2016,
    mileage: 112000,
    location: 'Nelson',
    region: 'South Island',
    type: 'Campervan',
    capacity: 2,
    selfContained: true,
    featured: false,
    description: 'Well-maintained Fiat with full self-contained setup.',
    imageUrl: 'https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=800',
    features: ['Self-Contained', 'Solar 300W', 'Shower', 'Toilet', 'Kitchen', 'Fridge'],
    seller: { name: 'Mark Taylor', rating: 4.7, phone: '+64 21 234 5678', email: 'mark@example.com' },
    buyBack: true,
    views: 278,
    postedDays: 5,
    wofExpiry: '2025-10-30',
    regoExpiry: '2025-09-25',
    createdAt: new Date()
  },
  {
    title: 'Subaru Sambar 2005 - Compact Adventure',
    price: 7200,
    year: 2005,
    mileage: 189000,
    location: 'Rotorua',
    region: 'North Island',
    type: 'Van',
    capacity: 2,
    selfContained: false,
    featured: false,
    description: 'Cute compact van, perfect for solo travelers or couples.',
    imageUrl: 'https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=800',
    features: ['4WD', 'Compact', 'Pop-top', 'Basic Kitchen', 'Economical'],
    seller: { name: 'Jenny Park', rating: 4.6, phone: '+64 27 567 8901', email: 'jenny@example.com' },
    buyBack: false,
    views: 145,
    postedDays: 8,
    wofExpiry: '2025-05-15',
    regoExpiry: '2025-04-20',
    createdAt: new Date()
  }
];

export const seedDatabase = async () => {
  console.log('🌱 Début du peuplement de la base de données...');
  
  try {
    const vansCollection = collection(db, 'vans');
    
    for (const van of vans) {
      const docRef = await addDoc(vansCollection, van);
      console.log(`✅ Van ajouté avec l'ID: ${docRef.id} - ${van.title}`);
    }
    
    console.log('🎉 Base de données peuplée avec succès!');
    console.log(`📊 Total: ${vans.length} vans ajoutés`);
  } catch (error) {
    console.error('❌ Erreur lors du peuplement:', error);
  }
};